name = "hmzelidrissi-ma"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[build]
command = "pnpm build"
cwd = "."

[env.production]
name = "hmzelidrissi-ma"

[env.preview]
name = "hmzelidrissi-ma-preview"
